import logging
import random
from typing import Dict, Any, List
from tools.base_tool import BaseTool
from mic.llm_loader import llm_instance # Import the shared LLM instance

logger = logging.getLogger(__name__)

class VideoCreatorTool(BaseTool):
    """
    A tool for simulating video creation from a script, enhanced with LLM for script breakdown.
    """

    def __init__(self, tool_name: str = "video_creator_tool"):
        super().__init__(tool_name)
        self.llm = llm_instance # Use the shared LLM instance

    @property
    def description(self) -> str:
        return "Generates simulated video files based on a script, style, and desired duration, using an LLM to break down the script into detailed scenes."

    @property
    def parameters(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "script": {"type": "string", "description": "A textual script describing the scenes and actions in the video."},
                "style": {"type": "string", "description": "The visual style of the video (e.g., 'animated', 'realistic', 'cartoon').", "default": "animated"},
                "duration_seconds": {"type": "integer", "description": "The desired duration of the video in seconds.", "default": 30}
            },
            "required": ["script"]
        }

    def execute(self, script: str, style: str = "animated", duration_seconds: int = 30) -> str:
        logger.info(f"Simulating video creation for script: '{script[:50]}...'")

        # Use LLM to break down the script into scenes
        llm_prompt = f"Break down the following video script into a detailed list of scenes, including visual descriptions and actions. Script: '{script}'"
        
        # Simulate LLM response for scene breakdown
        # In a real scenario, this would be an actual LLM call
        try:
            scene_breakdown_response = self.llm.get_response(llm_prompt)
            scene_breakdown = scene_breakdown_response.content
        except Exception as e:
            logger.warning(f"LLM call for scene breakdown failed: {e}. Using generic breakdown.")
            scene_breakdown = "Scene 1: [Visuals and actions]\nScene 2: [Visuals and actions]"


        # Simulate video file creation
        simulated_video_url = f"https://example.com/videos/{random.randint(10000, 99999)}.mp4"  # nosec B311

        video_description = f"""
Simulated Video Creation Report:
------------------------------------------
Script: "{script}"
Style: "{style}"
Duration: {duration_seconds} seconds
Simulated Video URL: '{simulated_video_url}'.

--- Detailed Scene Breakdown (Generated by LLM) ---
{scene_breakdown}
------------------------------------------
"""
        return video_description
